name: 'Setup SSH'
description: 'Setup SSH keys and known hosts'
inputs:
  target_ips:
    description: 'Comma-separated list of target IP addresses'
    required: true
  ssh_private_key:
    description: 'SSH private key (base64 encoded)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Add target hosts to known-hosts
      id: setup-ssh
      shell: bash
      env:
        TARGET_IPS: ${{ inputs.target_ips }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
      run: | 
        # Convert the input string to a bash array
        IFS=',' read -ra IP_ARRAY <<< "$TARGET_IPS"
        
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        PRIVATE_KEY_PATH=~/.ssh/id_rsa
        echo -n "$SSH_PRIVATE_KEY" | base64 --decode > "$PRIVATE_KEY_PATH"
        chmod 600 "$PRIVATE_KEY_PATH"

        eval "$(ssh-agent -s)"
        ssh-add "$PRIVATE_KEY_PATH"
        
        # Add each IP to known hosts
        for ip in "${IP_ARRAY[@]}"; do
          # Trim whitespace
          ip=$(echo "$ip" | xargs)
          echo "Adding IP to known hosts: $ip"
          ssh-keyscan -H "$ip" >> ~/.ssh/known_hosts
        done
        
        # Set correct permissions
        chmod 600 ~/.ssh/known_hosts

        # Set output
        echo "ssh_key_path=${PRIVATE_KEY_PATH}" >> $GITHUB_OUTPUT

outputs:
  ssh_key_path:
    description: 'Path to the SSH private key file'
    value: ${{ steps.setup-ssh.outputs.ssh_key_path }}
