name: 'Setup SSH'
description: 'Sets up SSH configuration with private key and known hosts'

inputs:
  target_ips:
    description: 'Comma-separated list of IP addresses to add to known hosts'
    required: true
  ssh_private_key:
    description: 'SSH Private Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Add target hosts to known-hosts
      shell: bash
      env:
        TARGET_IPS: ${{ inputs.target_ips }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
      run: | 
        # Convert the input string to a bash array
        IFS=',' read -ra IP_ARRAY <<< "$TARGET_IPS"
        
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
        # Add each IP to known hosts
        for ip in "${IP_ARRAY[@]}"; do
          # Trim whitespace
          ip=$(echo "$ip" | xargs)
          echo "Adding IP to known hosts: $ip"
          ssh-keyscan -H "$ip" >> ~/.ssh/known_hosts
        done
        
        # Set correct permissions
        chmod 600 ~/.ssh/known_hosts