- name: Run Api Gateway's docker compose
  hosts: api_gw
  become: true
  become_user: ec2-user

  tasks:
    - name: Ensure apiGw directory exists
      file:
        path: "~/apiGw"
        state: directory
    
    - name: Create a file and write success in it
      shell: echo "success" > ~/apiGw/file.txt
      args:
        creates: ~/apiGw/file.txt
