name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      TF_CLOUD_ORGANIZATION: "Form-iit"
      TF_API_TOKEN: "${{ secrets.TF_CLOUD_API_TOKEN }}"
      TF_WORKSPACE: "github-actions-pipeline"
      CONFIG_DIRECTORY: "src/terraform"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
      id: apply-upload
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Create deletion Run
      uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
      id: create-run
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        organization: ${{ env.TF_CLOUD_ORGANIZATION }}
        configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
        token: ${{ secrets.TF_CLOUD_API_TOKEN }}
        is_destroy: true
    
    - name: Apply Destroy Run
      uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
      id: apply-destroy
      with:
        run: ${{ steps.create-run.outputs.run_id }}
        token: ${{ secrets.TF_CLOUD_API_TOKEN }}