name: Run Apps

on:
    workflow_run:
        workflows: 
            - Infrastructure Deployment
        types:
            - completed

jobs:
    run_apps:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest

        steps:
          - name: Debug workflow context
            run: |
              echo "Workflow Run Head Branch: ${{ github.event.workflow_run.head_branch }}"
              echo "Workflow Run Head SHA: ${{ github.event.workflow_run.head_sha }}"
              echo "Event name: ${{ github.ref }}"