name: Run Services

on:
    workflow_run:
        workflows: 
            - "Ansible: setup docker on machines"
        types:
            - completed

jobs:
  get-eureka-host-ip:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: download machine instances IPs
        uses: dawidd6/action-download-artifact@v6
        with:
          name: instances
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "Ansible: setup docker on machines"
          run_id: ${{ github.event.workflow_run.id }}

      - name: Extract Eureka IP
        id: extract-eureka-ip
        run: |
          EUREKA_IP=$(jq -r '.eurekaIP' instances.json)
          API_GW_IP=$(jq -r '.apiGwIP' instances.json)
          echo "EUREKA_IP=$EUREKA_IP" >> $GITHUB_OUTPUT
          echo "API_GW_IP=$API_GW_IP" >> $GITHUB_OUTPUT
    outputs:
      eurekaIP: ${{ steps.extract-eureka-ip.outputs.EUREKA_IP }}
      apiGwIP: ${{ steps.extract-eureka-ip.outputs.API_GW_IP }}
  
  setup-ssh:
    needs: [get-eureka-host-ip]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: setup ssh keys and known hosts
        uses: ./.github/actions/setup-ssh
        with:
          target_ips: ${{ needs.get-eureka-host-ip.outputs.apiGwIP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  get-ansible-inventory:
    needs: 
      - setup-ssh
      - get-eureka-host-ip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: download ansible inventory
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ansible-inventory
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          workflow: "Ansible: setup docker on machines"
      
      - name: locate ansible inventory file
        run: |
          echo "inventory file is located at $GITHUB_WORKSPACE/inventory"
          chmod 600 inventory

      - name: ls
        run: |
          ls -l
          echo ========================================
          ls -l inventory
          echo ========================================
          ls -R 
          echo ========================================
          echo "Inventory content:"
          cat inventory
  
  run-eureka:
    needs: get-ansible-inventory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: run eureka
        run: |
          ansible-playbook -i inventory src/ansible/playbooks/run_eureka.yml
