name: Run Services

on:
    workflow_run:
        workflows: 
            - "Ansible: setup docker on machines"
        types:
            - completed

jobs:
  get-eureka-host-ip:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: download machine instances IPs
        uses: dawidd6/action-download-artifact@v6
        with:
          name: instances
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "Ansible: setup docker on machines"
          run_id: ${{ github.event.workflow_run.id }}

      - name: Extract Eureka IP
        id: extract-eureka-ip
        run: |
          EUREKA_IP=$(jq -r '.eurekaIP' instances.json)
          echo "Eureka IP is $EUREKA_IP"
          echo "EUREKA_IP=$EUREKA_IP" >> $GITHUB_OUTPUT
    
    outputs:
      eurekaIP: ${{ steps.extract-eureka-ip.outputs.EUREKA_IP }}
  
  setup-ssh:
    needs: [get-eureka-host-ip]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: setup ssh keys and known hosts
        uses: ./.github/actions/setup-ssh
        with:
          target_ips: ${{ needs.get-eureka-host-ip.outputs.eurekaIP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  get-ansible-inventory:
    needs: 
      - setup-ssh
      - get-eureka-host-ip
    runs-on: ubuntu-latest
    env:
      INVENTORY_PATH: ansible/inventory
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: download ansible inventory
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ansible-inventory
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          workflow: "Ansible: setup docker on machines"
          path: $INVENTORY_PATH

    outputs:
      inventoryPath: ${{ env.INVENTORY_PATH }}
  
  run-eureka:
    needs: get-ansible-inventory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: run eureka
        run: |
          ansible-playbook -i ${{ needs.get-ansible-inventory.outputs.inventoryPath }} ansible/playbooks/run-eureka.yml