# This workflow can be called within any other workflow then setup ssh private key within the caller's runner machine, then add the given ip addresses to the known hosts file
# @Inputs:
# target_ips : string [comma-separated list of ips] => .e.g "10.0.0.102, 172.168.0.1, 16.170.218.224"
# @Secrets:
# ssh_private_key: string

name: SSH Setup Workflow

on:
  workflow_call:
    inputs:
      target_ips:
        description: 'Array of IP addresses to add to known hosts'
        required: true
        type: string
      ssh_private_key:
        description: 'SSH Private Key'
        required: true
        type: string

jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Add target hosts to known-hosts
        env:
          TARGET_IPS: ${{ inputs.target_ips }}
        run: | 
          # Convert the input string to a bash array
          IFS=',' read -ra IP_ARRAY <<< "$TARGET_IPS"
          
          # Create .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          
          # Add each IP to known hosts
          for ip in "${IP_ARRAY[@]}"; do
            # Trim whitespace
            ip=$(echo "$ip" | xargs)
            echo "Adding IP to known hosts: $ip"
            ssh-keyscan -H "$ip" >> ~/.ssh/known_hosts
          done
          
          # Set correct permissions
          chmod 600 ~/.ssh/known_hosts
          
          # Optional: Display added hosts
          echo "Known hosts contents:"
          cat ~/.ssh/known_hosts

      - name: Sets up SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ inputs.ssh_private_key }}